[package]
name = "kika-does-async-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = {version = "0.6", features = ["codec", "io"] }
tokio-stream = "0.1"
tokio-tungstenite = "0.16"
futures-util = "0.3"
